CREATE DATABASE ProjectAPI;
GO;

USE ProjectAPI;
GO

CREATE TABLE Categories (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Active BIT NOT NULL DEFAULT 1,
    CreateBy NVARCHAR(100),
    CreateOn DATETIME2 NOT NULL,
    EditeBy NVARCHAR(100),
    EditeOn DATETIME2 NOT NULL
);

CREATE TABLE Products (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Active BIT NOT NULL DEFAULT 1,
    Description NVARCHAR(255),
    HasStock BIT NOT NULL,
    CategoryId UNIQUEIDENTIFIER NOT NULL,
    CreateBy NVARCHAR(100),
    CreateOn DATETIME2 NOT NULL,
    EditeBy NVARCHAR(100),
    EditeOn DATETIME2 NOT NULL,

    CONSTRAINT FK_Products_Categories FOREIGN KEY (CategoryId)
    REFERENCES Categories(Id) ON DELETE CASCADE
);